import logging

from odoo import api, SUPERUSER_ID

_logger = logging.getLogger(__name__)

# Taxes introduced by Law 30-26 (June 18, 2026). The previous rates remain
# valid for operations prior to the law, so new taxes are created instead
# of updating the existing ones. Each new tax is copied from its pre-law
# counterpart generated by the l10n_do chart template, keeping accounts,
# tags and repartition intact, and gets an external id following the chart
# template pattern so this script stays idempotent.
#
# The 15% withholding on technological services abroad supersedes the 27%
# remittance withholding (L253-12): the old tax is archived and the new
# one posts to its own payable account instead of reusing the one tied to
# L253-12.
LAW_30_26_TAXES = [
    (
        "ret_15_income_person",
        "ret_10_income_person",
        {
            "name": "Retención 15% ISR Honorarios a Físicas",
            "description": "-15% ISR Honorarios",
            "amount": -15.0,
        },
    ),
    (
        "ret_15_income_rent",
        "ret_10_income_rent",
        {
            "name": "Retención 15% ISR Alquileres a Físicas",
            "description": "-15% ISR Alquileres",
            "amount": -15.0,
        },
    ),
    (
        "ret_15_income_remittance_tech",
        "ret_27_income_remittance",
        {
            "name": "Retención 15% ISR Servicios Tecnológicos del Exterior",
            "description": "-15% ISR Serv. Tecnológicos",
            "amount": -15.0,
        },
    ),
]

TECH_TAX = "ret_15_income_remittance_tech"
TECH_ACCOUNT_XMLID = "do_niif_21030310"
TECH_ACCOUNT_CODE = "21030310"
TECH_ACCOUNT_NAME = "ISR Retenido por Servicios Tecnológicos del Exterior"


def _get_tax_account(tax):
    if "invoice_repartition_line_ids" in tax._fields:
        line = tax.invoice_repartition_line_ids.filtered(
            lambda l: l.repartition_type == "tax" and l.account_id
        )[:1]
        return line.account_id
    return tax.account_id


def _set_tax_account(tax, account):
    if "invoice_repartition_line_ids" in tax._fields:
        lines = (
            tax.invoice_repartition_line_ids + tax.refund_repartition_line_ids
        ).filtered(lambda l: l.repartition_type == "tax")
        lines.write({"account_id": account.id})
    else:
        tax.write({"account_id": account.id, "refund_account_id": account.id})


def _get_tech_account(env, company, source):
    account = env.ref(
        "l10n_do.%s_%s" % (company.id, TECH_ACCOUNT_XMLID),
        raise_if_not_found=False,
    )
    if account:
        return account
    Account = env["account.account"]
    # The chart of accounts is the client's to extend: the canonical code
    # 21030310 (the one the upstream template introduces) may already be
    # taken by an unrelated account, so never adopt an existing account by
    # code - create a new one on the first free code from there on.
    code = None
    for offset in range(90):
        candidate = str(21030310 + offset)
        if not Account.search(
            [("code", "=", candidate), ("company_id", "=", company.id)],
            limit=1,
        ):
            code = candidate
            break
    if not code:
        _logger.warning(
            "Company %s: no free code found for the tech withholding "
            "account, keeping the source tax account",
            company.name,
        )
        return Account.browse()
    old_account = _get_tax_account(source)
    if not old_account:
        return Account.browse()
    account = old_account.copy(
        default={"code": code, "name": TECH_ACCOUNT_NAME}
    )
    if code == TECH_ACCOUNT_CODE:
        # Same external id pattern the chart template generator uses, so
        # the script stays idempotent and consistent with the template.
        env["ir.model.data"].create(
            {
                "module": "l10n_do",
                "name": "%s_%s" % (company.id, TECH_ACCOUNT_XMLID),
                "model": "account.account",
                "res_id": account.id,
                "noupdate": True,
            }
        )
    else:
        _logger.warning(
            "Company %s: code %s was taken, tech withholding account "
            "created with code %s",
            company.name,
            TECH_ACCOUNT_CODE,
            code,
        )
    return account


def create_law_30_26_taxes(env):
    ir_model_data = env["ir.model.data"]
    for company in env["res.company"].search([]):
        for new_name, source_name, values in LAW_30_26_TAXES:
            source = env.ref(
                "l10n_do.%s_%s" % (company.id, source_name),
                raise_if_not_found=False,
            )
            if not source:
                continue
            if not env.ref(
                "l10n_do.%s_%s" % (company.id, new_name),
                raise_if_not_found=False,
            ):
                # On versions where taxes and tax groups carry a country,
                # country_id is a stored computed field: the copy recomputes
                # it from the company fiscal country while the tax group is
                # copied from the source. Legacy data can hold a mismatched
                # pair that would trip the tax group country constraint on
                # the new record, so make the pair explicit.
                if (
                    "country_id" in source._fields
                    and "country_id" in source.tax_group_id._fields
                ):
                    country = source.tax_group_id.country_id or source.country_id
                    if country:
                        values = dict(values, country_id=country.id)
                tax = env["account.tax"].search(
                    [
                        ("name", "=", values["name"]),
                        ("company_id", "=", company.id),
                        ("type_tax_use", "=", source.type_tax_use),
                    ],
                    limit=1,
                )
                if not tax:
                    tax = source.copy(default=values)
                    if new_name == TECH_TAX:
                        account = _get_tech_account(env, company, source)
                        if account:
                            _set_tax_account(tax, account)
                ir_model_data.create(
                    {
                        "module": "l10n_do",
                        "name": "%s_%s" % (company.id, new_name),
                        "model": "account.tax",
                        "res_id": tax.id,
                        "noupdate": True,
                    }
                )
                _logger.info(
                    "Company %s: created Law 30-26 tax %s", company.name, tax.name
                )
            if new_name == TECH_TAX and source.active:
                # The 15% technological services withholding supersedes the
                # 27% remittance withholding.
                source.active = False
                _logger.info(
                    "Company %s: archived tax %s", company.name, source.name
                )


def migrate(cr, version):
    env = api.Environment(cr, SUPERUSER_ID, {})
    create_law_30_26_taxes(env)
