import logging

from odoo import api, SUPERUSER_ID

_logger = logging.getLogger(__name__)

# Taxes introduced by Law 30-26 (June 18, 2026). The previous rates remain
# valid for operations prior to the law, so new taxes are created instead
# of updating the existing ones. Each new tax is copied from its pre-law
# counterpart generated by the l10n_do chart template, keeping accounts,
# tags and repartition intact, and gets an external id following the chart
# template pattern so this script stays idempotent.
LAW_30_26_TAXES = [
    (
        "ret_15_income_person",
        "ret_10_income_person",
        {
            "name": "Retención 15% ISR Honorarios a Físicas",
            "description": "-15% ISR",
            "amount": -15.0,
        },
    ),
    (
        "ret_15_income_rent",
        "ret_10_income_rent",
        {
            "name": "Retención 15% ISR Alquileres a Físicas",
            "description": "-15% ISR",
            "amount": -15.0,
        },
    ),
    (
        "ret_15_income_remittance_tech",
        "ret_27_income_remittance",
        {
            "name": "Retención 15% ISR Servicios Tecnológicos del Exterior",
            "description": "-15% ISR",
            "amount": -15.0,
        },
    ),
    (
        "tax_002_bank",
        "tax_0015_bank",
        {
            "name": "0.2% Transferencia Bancaria",
            "description": "0.2% Trans.",
            "amount": 0.2,
        },
    ),
]


def create_law_30_26_taxes(env):
    ir_model_data = env["ir.model.data"]
    for company in env["res.company"].search([]):
        for new_name, source_name, values in LAW_30_26_TAXES:
            if env.ref(
                "l10n_do.%s_%s" % (company.id, new_name),
                raise_if_not_found=False,
            ):
                continue
            source = env.ref(
                "l10n_do.%s_%s" % (company.id, source_name),
                raise_if_not_found=False,
            )
            if not source:
                continue
            # On versions where taxes and tax groups carry a country,
            # country_id is a stored computed field: the copy recomputes
            # it from the company fiscal country while the tax group is
            # copied from the source. Legacy data can hold a mismatched
            # pair that would trip the tax group country constraint on
            # the new record, so make the pair explicit.
            if (
                "country_id" in source._fields
                and "country_id" in source.tax_group_id._fields
            ):
                country = source.tax_group_id.country_id or source.country_id
                if country:
                    values = dict(values, country_id=country.id)
            tax = env["account.tax"].search(
                [
                    ("name", "=", values["name"]),
                    ("company_id", "=", company.id),
                    ("type_tax_use", "=", source.type_tax_use),
                ],
                limit=1,
            )
            if not tax:
                tax = source.copy(default=values)
            ir_model_data.create(
                {
                    "module": "l10n_do",
                    "name": "%s_%s" % (company.id, new_name),
                    "model": "account.tax",
                    "res_id": tax.id,
                    "noupdate": True,
                }
            )
            _logger.info(
                "Company %s: created Law 30-26 tax %s", company.name, tax.name
            )


def migrate(cr, version):
    env = api.Environment(cr, SUPERUSER_ID, {})
    create_law_30_26_taxes(env)
